language: node_js
node_js:
- 16
sudo: required
services:
  -docker

before_install:
  - docker build -t adamh/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true adamh/docker-react npm run test