language: node_js
node_js:
- 16
sudo: required
services:
  -docker

before_install:
  - docker build -t adamh/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true adamh/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "test-travis-ci"
  env: "Testtravisci-env"
  bucket_name: "elasticbeanstalk-eu-west-1-227980489147"
  bucket_path: "test-travis-ci"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY